import type {AppStyle} from '../types.js';

export interface Palette {
  bg: string;
  surface: string;
  fg: string;
  muted: string;
  accent: string;
  accentInk: string;
  border: string;
}

/** Deterministic palette per style. Premium-feeling, accessible contrast. */
export const paletteFor = (style: AppStyle): Palette => {
  switch (style) {
    case 'apple-like':
      return {bg: '#f5f5f7', surface: '#ffffff', fg: '#1d1d1f', muted: '#6e6e73', accent: '#0071e3', accentInk: '#ffffff', border: '#d2d2d7'};
    case 'dark':
      return {bg: '#0b0d12', surface: '#151922', fg: '#e6e9ef', muted: '#9aa4b2', accent: '#8b5cf6', accentInk: '#0e0717', border: '#232a36'};
    case 'minimal':
      return {bg: '#ffffff', surface: '#ffffff', fg: '#111827', muted: '#6b7280', accent: '#111827', accentInk: '#ffffff', border: '#e5e7eb'};
    case 'premium-saas':
    default:
      return {bg: '#0b0d12', surface: '#141821', fg: '#eef1f6', muted: '#9aa4b2', accent: '#14b8a6', accentInk: '#02110e', border: '#222a36'};
  }
};

/**
 * Shared design-system CSS: tokens, reset, spacing/typography scale, accessible
 * focus states, buttons, cards, and responsive helpers. Used by all static
 * templates so generated apps don't look like student projects.
 */
export const designSystemCss = (style: AppStyle): string => {
  const p = paletteFor(style);
  return `:root {
  --bg: ${p.bg};
  --surface: ${p.surface};
  --fg: ${p.fg};
  --muted: ${p.muted};
  --accent: ${p.accent};
  --accent-ink: ${p.accentInk};
  --border: ${p.border};
  --radius: 0.75rem;
  --space-1: 0.25rem; --space-2: 0.5rem; --space-3: 0.75rem; --space-4: 1rem;
  --space-6: 1.5rem; --space-8: 2rem; --space-12: 3rem;
  --shadow: 0 10px 30px rgba(0,0,0,.18);
  color-scheme: light dark;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  background: var(--bg);
  color: var(--fg);
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
h1, h2, h3 { line-height: 1.15; letter-spacing: -0.01em; margin: 0 0 var(--space-3); }
h1 { font-size: clamp(1.6rem, 4vw, 2.5rem); }
h2 { font-size: clamp(1.25rem, 3vw, 1.6rem); }
p { color: var(--muted); margin: 0 0 var(--space-4); }
a { color: var(--accent); }
.container { width: min(64rem, 100% - 2rem); margin-inline: auto; }
.btn {
  display: inline-flex; align-items: center; justify-content: center; gap: var(--space-2);
  padding: var(--space-3) var(--space-6); border: 0; border-radius: var(--radius);
  background: var(--accent); color: var(--accent-ink); font-weight: 600; cursor: pointer;
  transition: transform .08s ease, opacity .15s ease;
}
.btn:hover { transform: translateY(-1px); }
.btn:focus-visible { outline: 3px solid color-mix(in srgb, var(--accent) 50%, transparent); outline-offset: 2px; }
.btn.secondary { background: transparent; color: var(--fg); border: 1px solid var(--border); }
.card {
  background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius);
  padding: var(--space-6); box-shadow: var(--shadow);
}
.input {
  width: 100%; padding: var(--space-3) var(--space-4); border-radius: var(--radius);
  border: 1px solid var(--border); background: var(--surface); color: var(--fg);
}
.input:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
.muted { color: var(--muted); }
.empty-state { text-align: center; color: var(--muted); padding: var(--space-8); }
.visually-hidden {
  position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;
  overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; border: 0;
}
@media (max-width: 390px) {
  .container { width: calc(100% - 1.5rem); }
  .btn { width: 100%; }
}
`;
};

export const htmlHead = (title: string, extraLinks = ''): string =>
  `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <link rel="stylesheet" href="styles.css" />
${extraLinks}</head>`;

export const readme = (appName: string, description: string, openSteps: string[]): string =>
  `# ${appName}

${description}

Generated by ApeironCode (template-based, no API key required).

## Open

${openSteps.map((s) => `- \`${s}\``).join('\n')}

## Customize

- \`apeironcode improve "make this more premium"\`
- \`apeironcode fix\`
`;
